sudo: required
services:
 - docker

before_install:
 - docker build -t pizdebski/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pizdebski/complex-test npm test

after_success:
 - docker build -t pizdebski/multi-client:v3 ./client
 - docker build -t pizdebski/multi-nginx:v3 ./nginx
 - docker build -t pizdebski/multi-server:v3 ./server
 - docker build -t pizdebski/multi-worker:v3 ./worker


 # docker hub
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push pizdebski/multi-worker:v3
 - docker push pizdebski/multi-client:v3
 - docker push pizdebski/multi-nginx:v3
 - docker push pizdebski/multi-server:v3
