sudo: required
services:
 - docker

before_install:
 - docker build -t pizdebski/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pizdebski/complex-test npm test

after_success:
 - docker build -t pizdebski/multi-deployment-client ./client
 - docker build -t pizdebski/multi-deployment-nginx ./nginx
 - docker build -t pizdebski/multi-deployment-server ./server
 - docker build -t pizdebski/multi-deployment-worker ./worker


 # docker hub
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push pizdebski/multi-deployment-client
 - docker push pizdebski/multi-deployment-nginx
 - docker push pizdebski/multi-deployment-server
 - docker push pizdebski/multi-deployment-worker
